name: Build and Release on Tag

on:
  push:
    tags:
      - "*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Build binary
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags="-s -w -X github.com/amedoeyes/mason/cmd.version=$TAG" -o mason-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Compress binary
        run: |
          tar -czvf mason-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz mason-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mason-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
          path: mason-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz

  release:
    needs: build-and-release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Extract Tag Name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          artifacts: "*.tar.gz"
